//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotoideen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fotoideen.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen herunterladen.
        /// </summary>
        public static string btn_load {
            get {
                return ResourceManager.GetString("btn_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string btn_reset {
            get {
                return ResourceManager.GetString("btn_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        public static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade dir jetzt die verfügbaren Fotoideen.
        /// </summary>
        public static string infoNoItemsLoaded {
            get {
                return ResourceManager.GetString("infoNoItemsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        public static string infoTitle {
            get {
                return ResourceManager.GetString("infoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl von
        ///Wörtern.
        /// </summary>
        public static string lblRandom {
            get {
                return ResourceManager.GetString("lblRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.photowalkideas.com/about-photo-walk-ideas/.
        /// </summary>
        public static string linkOriginatorApp {
            get {
                return ResourceManager.GetString("linkOriginatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/spreadsheet/ccc?key=0AqSNciwmshHBdDU3d1JOeDV4RXh3TXdjMTNIUDczalE&amp;hl=de#gid=0.
        /// </summary>
        public static string linkSheet {
            get {
                return ResourceManager.GetString("linkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eigene Fotoideen hinzufügen.
        /// </summary>
        public static string linkSheetButton {
            get {
                return ResourceManager.GetString("linkSheetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetretten, bitte prüfen Sie ihre Internetverbindung!.
        /// </summary>
        public static string message_Exception {
            get {
                return ResourceManager.GetString("message_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Kommunikationsfehler aufgetretten, bitte versuchen Sie es noch einmal!.
        /// </summary>
        public static string message_WebExeption {
            get {
                return ResourceManager.GetString("message_WebExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen ist ein Begleiter für den Sonntagsausflug. Es soll dir helfen deine fotografischen Fähigkeiten zu verbessern.
        ///
        ///Fotoideen basiert auf der Idee des &quot;Photo Walk Ideas&quot; App für das iPhone (http://www.photowalkideas.com/about-photo-walk-ideas/). Leider ist dieses nur auf englisch erhältlich. Ich wollte eine einfache Anwendung schaffen, welche jeder Fotograf selbst erweitern und verbessern kann.
        ///
        ///Alle Stichworte werden direkt aus einer Excel-Tabelle ausgelesen. Diese liegt bei Google Texte &amp; Tabelle [rest of string was truncated]&quot;;.
        /// </summary>
        public static string readmeAbout {
            get {
                return ResourceManager.GetString("readmeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über Fotoideen.
        /// </summary>
        public static string readmeAboutTitle {
            get {
                return ResourceManager.GetString("readmeAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen hilft dir mit einer Liste von Stichwörtern bei einem fotografischen Kreativitätsloch oder um einfach einen anderen Blick auf gewohnte Motive zu finden. Dabei kannst du aus einer Liste von Themen wählen (Natur, Menschen, Urban, Sport, ...), und die Anzahl der Stichworte festlegen (3, 5, 10 ...). Fotoideen wird daraufhin eine Stichwortliste generieren. Deine Aufgabe ist es nun diese Stichworte fotografisch umzusetzen. Dabei kannst du versuchen alle Stichworte mit einem Bild festzuhalten (schwierig)  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string readmeHowItWorks {
            get {
                return ResourceManager.GetString("readmeHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie funktioniert das?.
        /// </summary>
        public static string readmeHowItWorksTitle {
            get {
                return ResourceManager.GetString("readmeHowItWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen unterliegt der CC BY-NC-SA 3.0 Lizenz (Namensnennung-Nicht-kommerziell-Weitergabe unter gleichen Bedingungen 3.0) Weitere Informationen zur Lizenz gibt es hier: http://creativecommons.org/licenses/by-nc-sa/3.0/de/.
        /// </summary>
        public static string readmeLicence {
            get {
                return ResourceManager.GetString("readmeLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenz.
        /// </summary>
        public static string readmeLicenceTitle {
            get {
                return ResourceManager.GetString("readmeLicenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoideen aktualisieren.
        /// </summary>
        public static string update_ideas {
            get {
                return ResourceManager.GetString("update_ideas", resourceCulture);
            }
        }
    }
}
